######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 17 21:33:31 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/a/u/austinmw/Desktop/diana4sb_jbsnyder_austinmw_lab5/qt/. \
               .

# Input
HEADERS += mainwindow.h mytimer.h ui_mainwindow.h
SOURCES += main.cpp mainwindow.cpp
